apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://democratic-csi.github.io/charts/"
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      values: |
        csiDriver:
          name: "org.democratic-csi.nfs"
        driver:
          existingConfigSecret: democratic-csi-driver-config
          config:
            # Helm needs this strictly for its templating logic!
            driver: zfs-generic-nfs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
