apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://democratic-csi.github.io/charts/"
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      values: |
        csiDriver:
          name: "org.democratic-csi.nfs"
        driver:
          config:
            driver: zfs-generic-nfs
            zfs:
              cli:
                sudoEnabled: true
              datasetParentName: logos/k8s/vols
              detachedSnapshotsDatasetParentName: logos/k8s/snapshots
              datasetEnableQuotas: true
              datasetEnableReservation: false
              datasetPermissionsMode: "0777"
              datasetPermissionsUser: 0
              datasetPermissionsGroup: 0
            sshConnection:
              host: 192.168.13.100
              port: 62222
              username: k8s
              privateKeySecretRef:
                name: democratic-csi-ssh-key
                key: private-key
            nfs:
              shareHost: 192.168.13.100
              shareStrategy: "setDatasetProperties"
              shareStrategySetDatasetProperties:
                properties:
                  sharenfs: "rw=@192.168.13.0/24,no_root_squash,no_subtree_check"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
