apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: home-gateway
  namespace: envoy-gateway-system
  annotations:
    io.cilium/lb-ipam-ips: "192.168.13.233"
    cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-staging"
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "argocd.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-server-tls
            namespace: argocd
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-secrets
  namespace: argocd
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Secret
