apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: home-gateway
  namespace: envoy-gateway-system
  annotations:
    io.cilium/lb-ipam-ips: "192.168.13.233"
    cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-production"
    io.cilium/l2-announcer: "true"
  labels:
    app.kubernetes.io/name: envoy
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: https-argocd
      protocol: HTTPS
      port: 443
      hostname: "argocd.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-frigate
      protocol: HTTPS
      port: 443
      hostname: "frigate.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: frigate-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-radarr
      protocol: HTTPS
      port: 443
      hostname: "radarr.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: radarr-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-sonarr
      protocol: HTTPS
      port: 443
      hostname: "sonarr.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: sonarr-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-prowlarr
      protocol: HTTPS
      port: 443
      hostname: "prowlarr.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: prowlarr-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-qbittorrent
      protocol: HTTPS
      port: 443
      hostname: "qbittorrent.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: qbittorrent-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-jellyfin
      protocol: HTTPS
      port: 443
      hostname: "jellyfin.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: jellyfin-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: https-seerr
      protocol: HTTPS
      port: 443
      hostname: "seerr.home.solazs.hu"
      tls:
        mode: Terminate
        certificateRefs:
          - name: seerr-server-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All

    - name: rtsp-listener
      protocol: TCP
      port: 8554
      allowedRoutes:
        namespaces:
          from: All # Allows your TCPRoute in the argocd/frigate namespace to attach to it
