apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "oci://docker.io/envoyproxy"
    chart: gateway-helm
    targetRevision: v1.7.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: envoy-gateway-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
