# 1. IoT VLAN Network Attachment
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan12-iot
  namespace: frigate
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "vlan12-iot",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp" 
      }
    }'
---
# 2. Video VLAN Network Attachment
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan55-video
  namespace: frigate
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "vlan55-video",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.55.150/24"
          }
        ]
      }
    }'
---
# 3. Updated Frigate ArgoCD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://blakeblackshear.github.io/blakeshome-charts/
    targetRevision: "7.8.0"
    chart: frigate
    helm:
      values: |
        # Multus network annotations to attach the secondary interfaces with STATIC MACs
        podAnnotations:
          k8s.v1.cni.cncf.io/networks: |-
            [
              {
                "name": "vlan12-iot",
                "mac": "02:F8:16:A7:E0:12" 
              },
              {
                "name": "vlan55-video",
                "mac": "02:F8:16:A7:E0:55"
              }
            ]
          
        envFromSecrets:
          - frigate-mqtt
          
        config: |
          mqtt:
            host: 192.168.13.200
            port: 1883
            user: frigate
            password: '{FRIGATE_MQTT_PASSWORD}'
          detectors:
            cpu:
              enabled: false
            coral:
              enabled: false
            openvino:
              enabled: true
              device: "AUTO"
            vaapi:
              enabled: true
              device: "/dev/dri/renderD128"
              
        persistence:
          media:
            enabled: true
            storageClass: democratic-csi-logos-nfs-media
            size: 1Ti
          config:
            enabled: true
            storageClass: democratic-csi-logos-nfs-media
            size: 1Gi
            
        tolerations:
          - key: "intel.feature.node.kubernetes.io/gpu"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "intel.feature.node.kubernetes.io/npu"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"
          intel.feature.node.kubernetes.io/npu: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true