# Intel GPU Device Plugin via Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://intel.github.io/helm-charts/
    path: intel
    chart: intel-device-plugins-gpu
    targetRevision: 0.34.0
    # helm:
    #   valueFiles:
    #     - values.yaml # Place your custom values.yaml in the same app directory or configure as needed
  destination:
    server: https://kubernetes.default.svc
    namespace: intel-device-plugins-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true