apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/intel/intel-device-plugins-for-kubernetes.git
    targetRevision: v0.35.0
    path: deployments/operator/default
  destination:
    server: https://kubernetes.default.svc
    namespace: intel-device-plugins-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
