apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://intel.github.io/helm-charts
    targetRevision: "0.35.0"
    chart: device-plugins-operator
    helm:
      values: |
    operator:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "intel.feature.node.kubernetes.io/npu"
                    operator: "In"
                    values:
                      - "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
