apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan12-iot
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vlan12-iot",
    "mode": "bridge",
    "ipam": {
      "type": "dhcp"
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan13-home
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vlan13-home",
    "mode": "bridge",
    "ipam": {
      "type": "dhcp"
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan88-mgmt
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vlan88-mgmt",
    "mode": "bridge",.
    "ipam": {
      "type": "dhcp"
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan55-video
  annotations:
    k8s.v1.cni.cncf.io/nodeSelector: '{
      "kubernetes.io/hostname": "mjolnir"
    }'
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vlan55-video",
    "mode": "bridge",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.55.0/24"
    }
  }'
