# Intel GPU Device Plugin via Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-gpu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    path: nvdp
    chart: nvidia-device-plugin
    # targetRevision: 0.18.2
    # helm:
    #   valueFiles:
    #     - values.yaml # Place your custom values.yaml in the same app directory or configure as needed
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true