# Intel GPU Device Plugin via Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    path: nvdp
    chart: nvidia-device-plugin
    targetRevision: 0.18.2
    helm:
      parameters:
        - name: gfd.enabled
          value: "true"
        - name: nfd.enabled
          value: "false"
        - name: deviceDiscoveryStrategy
          value: "nvml"
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true