apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://kubernetes-sigs.github.io/external-dns/"
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        provider:
          name: rfc2136

        # Pull the TSIG secret securely from the Ansible-created Secret
        env:
          - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
            valueFrom:
              secretKeyRef:
                name: external-dns-tsig
                key: tsig-secret
                
        extraArgs:
          - --rfc2136-host=192.168.13.200
          - --rfc2136-port=53
          - --rfc2136-zone=home.solazs.hu
          - --rfc2136-tsig-secret-alg=hmac-sha256
          - --rfc2136-tsig-keyname=k8s
          
        # Tell ExternalDNS to watch Ingresses (which Cilium manages) and Services
        sources:
          - ingress
          - service
          
        # Restrict ExternalDNS to only modify records in this specific zone
        domainFilters:
          - home.solazs.hu
          
        # Prevent ExternalDNS from deleting records it didn't create
        policy: sync

        # Add TXT registry to keep track of which records ExternalDNS owns
        txtOwnerId: "k8s-cluster"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
