apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://kubernetes-sigs.github.io/external-dns/"
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        provider:
          name: rfc2136

        # Step 4: Add permissions for the Gateway API resources
        rbac:
          create: true
          additionalPermissions:
            - apiGroups: ["gateway.networking.k8s.io"]
              resources: ["gateways", "httproutes"]
              verbs: ["get", "watch", "list"]

        env:
          - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
            valueFrom:
              secretKeyRef:
                name: external-dns-tsig # Ensure this secret is moved to 'external-dns' namespace!
                key: tsig-secret
                
        extraArgs:
          - --rfc2136-host=192.168.13.200
          - --rfc2136-port=53
          - --rfc2136-zone=home.solazs.hu
          - --rfc2136-tsig-secret-alg=hmac-sha256
          - --rfc2136-tsig-keyname=k8s
          - --rfc2136-create-ptr
          
        sources:
          - ingress
          - service
          - gateway-httproute
          - gateway-grpcroute
          
        domainFilters:
          - home.solazs.hu
          - 13.168.192.in-addr.arpa
          
        policy: sync
        txtOwnerId: "k8s-cluster"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns # New home for the app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensures the namespace exists before deploy
