apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: whereabouts
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: whereabouts
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - list
          - watch
      - apiGroups:
          - whereabouts.cni.cncf.io
        resources:
          - ippools
          - overlappingrangeipreservations
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: whereabouts
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: whereabouts
    subjects:
      - kind: ServiceAccount
        name: whereabouts
        namespace: kube-system
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: whereabouts
      namespace: kube-system
      labels:
        app: whereabouts
    spec:
      selector:
        matchLabels:
          app: whereabouts
      template:
        metadata:
          labels:
            app: whereabouts
        spec:
          serviceAccountName: whereabouts
          containers:
            - name: whereabouts
              image: ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.1
              command: ["/bin/sh", "-c", "sleep infinity"]
              volumeMounts:
                - name: cni-bin
                  mountPath: /host/opt/cni/bin
          volumes:
            - name: cni-bin
              hostPath:
                path: /opt/cni/bin
